### ISSUE TITLE
cannot read segy file

### ISSUE THREAD

**Issue by israelklink** [cultpenguin/segypy#3]
I'd like to ask your help for a problem I'm encountering. I need to read a data in segy with 2G, this data is a given test. For me it would be very important to be able to use the SH and STH, however, I can not because this data is big.

Would you have any solution to help me?

**Comment by cultpenguin** [comment]
You can read the full SH and STH using : 
#%% Read only SegyHeader and SegyTraceHeader
SH = segypy.getSegyHeader(filename)
STH = segypy.getAllSegyTraceHeaders(SH)
