### ISSUE TITLE
Read JUST STH

### ISSUE THREAD

**Issue by israelklink** [cultpenguin/segypy#4]
There are a possibility to read STH?

# Get only SegyHeader
SH = segypy.getSegyHeader(filename);

**Comment by cultpenguin** [comment]
Yes. you can read all SegyTraceHeaders using 

filename='shogather.sgy'
SH = segypy.getSegyHeader(filename)
STH = segypy.getAllSegyTraceHeaders(SH)

There was a rounding error that is now fixed in version 0.57. Update and it should work.
